spring:
  ai:
    azure:
      openai:
        api-key: ${AZURE_OPENAI_APIKEY}
        endpoint: ${AZURE_OPENAI_ENDPOINT}
        chat:
          options:
            deployment-name: doc3
            temperature: 0.7
  cloud:
    function:
      definition: downloadFileJson
